Restaurants Web App/Models/Schedule.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Restaurants.Models
{
    public class Schedule
    { 
        [Key]
        public int Note { get; set; }
        [ForeignKey("Restaurant")]
        public int RestaurantId { get; set; }
        public Restaurant Restaurant { get; set; }
        public DateTime Date { get; set; }
        public TimeSpan From { get; set; }
        public TimeSpan To { get; set; }
        [ForeignKey("Employee")]
        public int EmployeeId { get; set; }
        public Employee Employee { get; set; }
    }
}

Restaurants Web App/Controllers/ScheduleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Restaurants.Models;

namespace Restaurants.Controllers
{
    /// <summary>
    /// <c>ScheduleController</c> is responsible for handling requests that relate to the schedule.
    /// </summary>
    public class ScheduleController : Controller
    {
        public const string MorningShift = "утренняя", EveningShift = "вечерняя";
        public const int HoursInShift = 7;

        private static readonly int[] DaysInMonth = new int[MonthsInYear];

        private const int StartTime = 10, EndTime = 24;
        private const int MonthsInYear = 12;

        static ScheduleController()
        {
            int i = 0;
            DaysInMonth[i++] = 31;
            DaysInMonth[i++] = 28;
            DaysInMonth[i++] = 31;
            DaysInMonth[i++] = 30;
            DaysInMonth[i++] = 31;
            DaysInMonth[i++] = 30;
            DaysInMonth[i++] = 31;
            DaysInMonth[i++] = 31;
            DaysInMonth[i++] = 30;
            DaysInMonth[i++] = 31;
            DaysInMonth[i++] = 30;
            DaysInMonth[i++] = 31;
        }

        private EmployeeContext db = new EmployeeContext();


        /// <summary>
        /// Shows the scheduling menu. It contains buttons for generating and displaying schedules.
        /// </summary>
        /// <returns>A view with the menu.</returns>
        [HttpGet]
        public ActionResult Menu()
        {
            ViewBag.Restaurants = db.Restaurants.ToList();
            return View();
        }


        /// <summary>
        /// Shows a schedule for the specified month if the "Show" button on the menu page is pressed. 
        /// Generates a new schedule FOR ALL restaurants and shows FOR SPECIFIED if the "Generate" button is pressed.
        /// </summary>
        /// <remarks>
        /// Unfortunately it can't take into account the attestations :(
        /// Therefore the scedule is generated like there's no any cuisines in the rastaurants.
        /// </remarks>
        /// <param name="request">A value from a pressed button</param>
        /// <param name="month">A month that a schedule should be generated for</param>
        /// <param name="restaurantId">A restaurant that a schedule should be generated for</param>
        /// <returns>A view with schedule if parameters are correct or an error page otherwise</returns>
        [HttpGet]
        public ActionResult Show(string request, int month, int restaurantId)
        {
            if (month < 1 || month > 12 || db.Restaurants.First(x => x.Id == restaurantId) == null)
            {
                return new HttpStatusCodeResult(400);
            }

            if (request == "Составить")
            {
                db.Schedules.RemoveRange(db.Schedules.Where(x => x.Date.Month == month));
                db.SaveChanges();

                GenerateSchedule(month, restaurantId);

                SelectSchedule(month, restaurantId);
                return View();
            }
            else if (request == "Показать")
            {
                SelectSchedule(month, restaurantId);

                ViewBag.RestaurantId = restaurantId;
                ViewBag.Month = month;

                return View();
            }
            else
            {
                return new HttpStatusCodeResult(400);
            }            
        }


        // Writes a schedule for the specified month and restaurant into ViewBag.
        private void SelectSchedule(int month, int restaurantId)
        {
            var scheduleList = from schedule in db.Schedules.Include("Employee")
                               where schedule.RestaurantId == restaurantId && schedule.Date.Month == month
                               orderby schedule.Date
                               select schedule;

            ViewBag.ScheduleList = scheduleList.ToList();

            ViewBag.WorkersPerDay = (from schedule in scheduleList
                                     group schedule by schedule.Date into dateGroup
                                     select dateGroup.Count()).ToList();
        }


        private void GenerateSchedule(int month, int restaurantId)
        {
            List<Employee> employees = db.Employees.Include("Attestations").ToList();

            for (int i = 1; i <= DaysInMonth[month - 1]; i++)
            {
                EmployeeList workingToday = new EmployeeList(employees.FindAll(e => WorksToday(e, month, i)));
                workingToday.Sort(new EmployeeComparer());

                foreach (Restaurant restaurant in db.Restaurants)
                {
                    List<Employee> selected = new List<Employee>();
                    int totalHours = 0;

                    Employee current = workingToday.FirstAppropriate(totalHours, selected);

                    while (true)
                    {

                        if (current == null)
                        {
                            if (totalHours < HoursInShift)
                            {
                                totalHours = 0;

                                Employee next = workingToday.LastAppropriate(totalHours, selected);
                                if (next != null)
                                {
                                    selected.Add(next);
                                }

                                totalHours = HoursInShift;

                                if ((current = workingToday.FirstAppropriate(totalHours, selected)) == null)
                                {
                                    break;
                                }
                            }
                            else
                            {
                                break;
                            }
                        }

                        if (totalHours + current.AmountOfWorkingHours < HoursInShift * 2)
                        {
                            selected.Add(current);
                            totalHours += current.AmountOfWorkingHours;
                            current = workingToday.FirstAppropriate(totalHours, selected);
                            continue;
                        }
                        else if (totalHours + current.AmountOfWorkingHours == HoursInShift * 2)
                        {
                            selected.Add(current);
                            totalHours += current.AmountOfWorkingHours;
                            break;
                        }
                        else
                        {
                            Employee next = workingToday.NextAppropriate(workingToday.IndexOf(current) + 1, totalHours, selected);
                            if (next != null)
                            {
                                current = next;
                            }
                            else
                            {
                                Employee last = selected.Count > 0 ? selected.Last() : null;

                                if (last != null)
                                {
                                    selected.Remove(last);
                                    totalHours -= last.AmountOfWorkingHours;
                                    next = workingToday.NextAppropriate(workingToday.IndexOf(last) + 1, totalHours, selected);
                                }
                                else
                                {
                                    selected.Add(current);
                                    totalHours += current.AmountOfWorkingHours;
                                    break;
                                }
                                
                                if (next == null)
                                {
                                    selected.Add(last);
                                    totalHours += last.AmountOfWorkingHours;                                  

                                    selected.Add(current);
                                    totalHours += current.AmountOfWorkingHours;
                                    break;
                                }
                                else
                                {
                                    selected.Add(next);
                                    totalHours += next.AmountOfWorkingHours;

                                    current = workingToday.FirstAppropriate(totalHours, selected);
                                }
                            }
                        }
                    }

                    WriteScheduleListToDatabase(workingToday, selected, restaurant, month, i);
                }
            }

            db.SaveChanges();
        }


        private void WriteScheduleListToDatabase(List<Employee> workingToday, List<Employee> selected,
            Restaurant restaurant, int month, int day)
        {
            List<Schedule> scheduleItems = new List<Schedule>();

            int totalHours = 0;

            foreach (Employee e in selected)
            {
                workingToday.Remove(e);

                Schedule scheduleItem = new Schedule();

                scheduleItem.RestaurantId = restaurant.Id;
                scheduleItem.Restaurant = restaurant;
                scheduleItem.EmployeeId = e.Id;
                scheduleItem.Employee = e;
                scheduleItem.Date = Today(month, day);

                bool eveningShift = false;
                if (e.Shift == null || (eveningShift = e.Shift == EveningShift))
                {
                    if (eveningShift && totalHours < HoursInShift)
                    {
                        totalHours = HoursInShift;
                    }

                    if (totalHours + e.AmountOfWorkingHours <= HoursInShift * 2)
                    {
                        scheduleItem.From = new TimeSpan(StartTime + totalHours, 0, 0);

Restaurants Web App/Views/Schedule/Menu.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/Content/css/header.css" />
    <link rel="stylesheet" href="~/Content/css/menu.css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600&amp;subset=cyrillic" rel="stylesheet">
    <title>Menu</title>
</head>
<body> 
    <table id="header">
        <tr>
            <td>
                @using (Html.BeginForm("Show", "Schedule", FormMethod.Get))
                {
                    @:Расписание на
                    <select name="month">
                        <option value="1">январь</option>
                        <option value="2">февраль</option>
                        <option value="3">март</option>
                        <option value="4">апрель</option>
                        <option value="5">май</option>
                        <option value="6">июнь</option>
                        <option value="7">июль</option>
                        <option value="8">август</option>
                        <option value="9">сентябрь</option>
                        <option value="10">октябрь</option>
                        <option value="11">ноябрь</option>
                        <option value="12">декабрь</option>
                    </select>
                    @:для ресторана
                    <select name="restaurantId" style="margin-right: 20px">
                        @foreach (Restaurants.Models.Restaurant restaurant in ViewBag.Restaurants)
                        {
                            <option value="@restaurant.Id">@restaurant.Id</option>
                        }
                    </select>
                    <input class="headerButton" name="request" type="submit" value="Составить">
                    <input class="headerButton" name="request" type="submit" value="Показать">
                }
            </td>
        </tr>      
    </table>
    @using (Html.BeginForm("Index", "Home", FormMethod.Get))
    {
        <input id="back" class="headerButton" type="submit" value="Вернуться" />
    }       
</body>
</html>

Restaurants Web App/Views/Schedule/Show.cshtml
@model IEnumerable<Restaurants.Models.Schedule>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Schedule</title>
    <link rel="stylesheet" href="~/Content/css/header.css" />
    <link rel="stylesheet" href="~/Content/css/show.css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600&amp;subset=cyrillic" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js" type="text/javascript"></script>
    <script>
        window.onscroll = function () {
            if ((window.pageYOffset || document.documentElement.scrollTop) > 100) {
                $("#up").css("visibility", "visible");
            } else {
                $("#up").css("visibility", "hidden");
            }
        }

        function scrollToTop() {
            $("html, body").animate({
                scrollTop: 0
            }, 500);
        }
    </script>
</head>
<body>
    <div id="container">
        @{
            if (((List<Restaurants.Models.Schedule>)ViewBag.ScheduleList).Count == 0)
            {
                <table id="header">
                    <tr>
                        <th>                            
                            @using (Html.BeginForm("Show", "Schedule", FormMethod.Get))
                            {
                                @:На этот месяц расписание еще не составлено :(
                                @Html.Hidden("month", ViewBag.Month as string)
                                @Html.Hidden("restaurantId", ViewBag.RestaurantId as string)
                                <input class="headerButton" name="request" type="submit" value="Составить"
                                       style="margin-left: 10px" />
                            }
                        </th>
                    </tr>
                </table>
                using (Html.BeginForm("Menu", "Schedule", FormMethod.Get))
                {
                    <input id="back" class="headerButton" type="submit" value="Вернуться" />
                }
            }
            else
            {
                DateTime lastDate = new DateTime();

                int datePointer = 0;
                string backgroundColor = null;

                <table id="header">
                    <tr>
                        <th></th>
                        <th class="date">Дата</th>
                        <th class="time">Время работы</th>
                        <th class="name">Ф.И.О.</th>
                        <th></th>
                    </tr>
                </table>
                using (Html.BeginForm("Menu", "Schedule", FormMethod.Get))
                {
                    <input id="back" class="headerButton" type="submit" value="Вернуться" />
                }
                <input id="up" type="button" value="Наверх" onclick="scrollToTop()" />
                <table id="schedule">
                    @for (int i = 0; i < ViewBag.ScheduleList.Count; i++)
                    {
                        <tr>
                            @{
                                Restaurants.Models.Schedule schedule = ViewBag.ScheduleList[i];
                                if (schedule.Date != lastDate)
                                {
                                    backgroundColor = datePointer % 2 == 0 ? "#F5F5F5" : "#EFEFEF";
                                    <td class="date" rowspan="@ViewBag.WorkersPerDay[datePointer]" 
                                        style="text-align: center; background-color: @backgroundColor">
                                        @schedule.Date.ToShortDateString()
                                    </td>
                                    datePointer++;
                                }

                                string fromClass, toClass;
                                fromClass = toClass = "inTime";
                                if (lastDate != null && schedule.Date == lastDate && schedule.From < ViewBag.ScheduleList[i - 1].To) {
                                    fromClass = "beginsEarly";
                                }
                                else if (schedule.Date != lastDate && schedule.From.Hours > 10)
                                {
                                    fromClass = "notInTime";
                                }

                                if (i < ViewBag.ScheduleList.Count - 1 && schedule.Date != ViewBag.ScheduleList[i + 1].Date &&
                                                !schedule.To.Equals(new TimeSpan(0, 0, 0)))
                                {
                                    toClass = "notInTime";
                                }

                                lastDate = schedule.Date;

                                <td class="time" style="text-align: center; background-color: @backgroundColor">
                                    с
                                    <span class="@fromClass">@schedule.From.ToString(@"hh\:mm")</span>
                                    до
                                    <span class="@toClass">@schedule.To.ToString(@"hh\:mm")</span>
                                </td>

                                Restaurants.Models.Employee employee = schedule.Employee;
                                string name = employee.LastName;
                                name += " " + employee.FirstName[0] + ".";
                                if (employee.Patronymic != null)
                                {
                                    name += " " + employee.Patronymic[0] + ".";
                                }

                                <td class="name" style="background-color: @backgroundColor">
                                    <span>@name</span>
                                </td>
                            }
                        </tr>
                    }
                </table>
            }
        }
    </div>
</body>
</html>